# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3105af7fdcb05d7bf051aaa1dd4f0fef0675f84fa7ec7bd22e52fd5f3038567c5cfe07f1b346b9e8ac68905a7d985ad9ab850cf53aa0f8c11dfc52634b01fb1

test:
  secret_key_base: f49b925f1c45af75cd0fb153967de3fe854cca875c1540a9c688c9ca551126b9d7ea79d2e1043feaf2b89602ce57e8e5c306679129cb14a14b81a84b63764b71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
